#!/usr/bin/env node
import OpenAI from 'openai'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = resolve(import.meta.dirname, '..')
const outPath = resolve(root, 'data/openai_redteam_status.json')
const publicOutPath = resolve(root, 'public/data/openai_redteam_status.json')

function loadDotenv() {
  try {
    const text = readFileSync(resolve(root, '.env'), 'utf8')
    for (const rawLine of text.split(/\r?\n/)) {
      const line = rawLine.trim()
      if (!line || line.startsWith('#') || !line.includes('=')) continue
      const [key, ...rest] = line.split('=')
      if (!process.env[key]) {
        process.env[key] = rest.join('=').trim().replace(/^['"]|['"]$/g, '')
      }
    }
  } catch {
    // .env is optional; shell environment is preferred for Codex runs.
  }
}

function readText(path, maxChars = 12000) {
  try {
    return readFileSync(resolve(root, path), 'utf8').slice(0, maxChars)
  } catch {
    return ''
  }
}

function readJsonWithoutRedteam(path, maxChars = 14000) {
  try {
    const payload = JSON.parse(readFileSync(resolve(root, path), 'utf8'))
    if (payload?.integrations?.openai_redteam) {
      payload.integrations.openai_redteam = {
        status: 'omitted_for_current_review',
        note: 'Previous red-team output is intentionally omitted to avoid self-review feedback.',
      }
    }
    return JSON.stringify(payload).slice(0, maxChars)
  } catch {
    return ''
  }
}

function extractJson(text) {
  const trimmed = text.trim()
  try {
    return JSON.parse(trimmed)
  } catch {
    const match = trimmed.match(/\{[\s\S]*\}/)
    if (!match) return null
    try {
      return JSON.parse(match[0])
    } catch {
      return null
    }
  }
}

function normalizeFinding(item) {
  if (!item || typeof item !== 'object') return null
  return {
    severity: String(item.severity || 'info').toLowerCase(),
    area: String(item.area || 'general').slice(0, 80),
    finding: String(item.finding || '').slice(0, 400),
    fix: String(item.fix || '').slice(0, 400),
  }
}

function writeStatus(status) {
  const payload = {
    schema: 'aws-biopharma.openai-redteam-status.v1',
    generated_at: new Date().toISOString(),
    ...status,
  }
  mkdirSync(resolve(root, 'data'), { recursive: true })
  mkdirSync(resolve(root, 'public/data'), { recursive: true })
  writeFileSync(outPath, `${JSON.stringify(payload, null, 2)}\n`)
  writeFileSync(publicOutPath, `${JSON.stringify(payload, null, 2)}\n`)
  console.log(JSON.stringify(payload, null, 2))
}

loadDotenv()

const apiKeyPresent = Boolean(process.env.OPENAI_API_KEY)
const fallbackModel = process.env.OPENAI_MODEL || 'gpt-4o-mini'
const preferredModels = [
  process.env.OPENAI_MODEL,
  'gpt-4.1',
  'gpt-4.1-mini',
  'gpt-4o',
  'gpt-4o-mini',
  'o4-mini',
  'o3-mini',
  'gpt-5',
  'gpt-5-mini',
  'gpt-5-nano',
].filter(Boolean)
const requestedModels = (process.env.OPENAI_REDTEAM_MODELS || '')
  .split(',')
  .map((item) => item.trim())
  .filter(Boolean)
const maxModels = Math.max(1, Number.parseInt(process.env.OPENAI_REDTEAM_MAX_MODELS || '8', 10))

if (!apiKeyPresent) {
  writeStatus({
    status: 'not_configured',
    provider: 'openai',
    model_id: fallbackModel,
    model_ids: [],
    api_key_present: false,
    note: 'OPENAI_API_KEY is not present in the shell environment or .env.',
  })
  process.exit(1)
}

const evidenceBundle = {
  package_json: readText('package.json', 4000),
  readme: readText('README.md', 8000),
  data_policy: readText('DATA_POLICY.md', 8000),
  hackday_status: readText('HACKDAY_STATUS.md', 8000),
  dashboard_html: readText('public/index.html', 8000),
  dashboard_js: readText('public/app.js', 14000),
  dashboard_css: readText('public/styles.css', 8000),
  dashboard_snapshot_without_prior_redteam: readJsonWithoutRedteam('data/dashboard_snapshot.json', 14000),
}

const roles = [
  {
    id: 'live_dashboard_viability',
    label: 'Live dashboard viability',
    prompt:
      'Review whether this static dashboard is viable for teammate review. Focus on broken data loads, blank screens, missing status surfaces, confusing run instructions, and whether a local server URL is enough. The OpenAI red-team panel is being generated by this run, so its absence in the supplied pre-review snapshot is not a blocker.',
  },
  {
    id: 'secrets_and_client_safety',
    label: 'Secrets and client safety',
    prompt:
      'Red-team for secret leakage and unsafe client-side API usage. Focus on API keys, .env handling, public data files, browser JS, repo status assumptions, and whether OpenAI is called only server/local-side.',
  },
  {
    id: 'claim_ceiling_and_rights',
    label: 'Claim ceiling and rights',
    prompt:
      'Red-team biopharma claim risk and data-rights posture. Focus on clinical/therapeutic overclaiming, provider output redistribution, and whether the dashboard stays within a reproducible evidence workflow claim ceiling.',
  },
]

const system = [
  'You are a concise red-team reviewer for an AWS Biopharma hackathon dashboard.',
  'Use only the supplied repo evidence.',
  'Do not request or reveal secrets.',
  'A missing optional provider token is not a blocker when the dashboard explicitly reports the provider as not configured.',
  'Bright Data is optional in this demo; token_not_visible is a visible integration status, not a dashboard failure.',
  'The current OpenAI red-team result is being generated now; do not mark it as missing based on the pre-review snapshot.',
  'A blocker must prevent teammate review, expose a secret, break the dashboard render path, or violate the claim/data-rights ceiling.',
  'Do not infer blank sections unless the supplied JavaScript or snapshot proves that rendering will fail.',
  'Return JSON only with keys: verdict, blockers, findings, recommended_next_step.',
  'verdict must be pass, pass_with_notes, or fail.',
  'blockers must be an array of short strings.',
  'findings must be an array of objects with severity, area, finding, fix.',
].join(' ')

const client = new OpenAI()

async function resolveModelMatrix() {
  if (requestedModels.length > 0) {
    return [...new Set(requestedModels)].slice(0, maxModels)
  }

  try {
    const available = await client.models.list()
    const ids = new Set(available.data.map((modelInfo) => modelInfo.id))
    const selected = [...new Set(preferredModels)].filter((id) => ids.has(id)).slice(0, maxModels)
    if (selected.length > 0) return selected
  } catch {
    // Fall through to the explicitly configured fallback model.
  }

  return [fallbackModel]
}

try {
  const modelIds = await resolveModelMatrix()
  const reviewJobs = modelIds.flatMap((modelId) => roles.map((role) => ({ role, modelId })))
  const results = await Promise.all(
    reviewJobs.map(async ({ role, modelId }) => {
      try {
      const response = await client.chat.completions.create({
        model: modelId,
        temperature: 0,
        max_tokens: 650,
        response_format: { type: 'json_object' },
        messages: [
          { role: 'system', content: system },
          {
            role: 'user',
            content: `${role.prompt}\n\nRepo evidence JSON:\n${JSON.stringify(evidenceBundle)}`,
          },
        ],
      })
      const text = response.choices?.[0]?.message?.content || ''
      const parsed = extractJson(text)
      const findings = Array.isArray(parsed?.findings)
        ? parsed.findings.map(normalizeFinding).filter(Boolean)
        : []
      return {
        id: `${role.id}:${modelId}`,
        role_id: role.id,
        label: role.label,
        model_id: modelId,
        completed: true,
        verdict: ['pass', 'pass_with_notes', 'fail'].includes(parsed?.verdict)
          ? parsed.verdict
          : 'fail',
        blockers: Array.isArray(parsed?.blockers)
          ? parsed.blockers.map((item) => String(item).slice(0, 240))
          : ['Reviewer did not return parseable blockers.'],
        findings,
        recommended_next_step: String(parsed?.recommended_next_step || '').slice(0, 400),
        response_id: response.id || null,
      }
      } catch (error) {
        return {
          id: `${role.id}:${modelId}`,
          role_id: role.id,
          label: role.label,
          model_id: modelId,
          completed: false,
          verdict: 'fail',
          blockers: [],
          findings: [
            {
              severity: 'warning',
              area: 'openai_model_call',
              finding: `OpenAI reviewer call did not complete for ${modelId}: ${String(
                error?.message || error,
              ).slice(0, 220)}`,
              fix: 'Use another available OpenAI model or set OPENAI_REDTEAM_MODELS to a compatible model list.',
            },
          ],
          recommended_next_step: 'Retry with a compatible OpenAI model if broader model coverage is required.',
          response_id: null,
        }
      }
    }),
  )

  const completedResults = results.filter((result) => result.completed)
  const blockers =
    completedResults.length === 0
      ? ['No OpenAI red-team reviewer completed.']
      : [...new Set(completedResults.flatMap((result) => result.blockers || []))]
  const failCount = completedResults.filter((result) => result.verdict === 'fail').length
  const modelErrors = results.filter((result) => !result.completed).length
  const status = failCount > 0 || blockers.length > 0 ? 'needs_review' : 'pass'
  writeStatus({
    status,
    provider: 'openai',
    model_id: modelIds[0],
    model_ids: modelIds,
    api_key_present: true,
    role_count: roles.length,
    reviewer_count: results.length,
    completed_reviewer_count: completedResults.length,
    model_error_count: modelErrors,
    blockers,
    reviewers: results,
    note:
      status === 'pass'
        ? 'OpenAI red-team model matrix found no blockers for teammate dashboard review.'
        : 'OpenAI red-team fanout found blockers or failed reviewer verdicts.',
  })
  process.exit(status === 'pass' ? 0 : 2)
} catch (error) {
  writeStatus({
    status: 'fail',
    provider: 'openai',
    model_id: model,
    api_key_present: true,
    error_type: error?.constructor?.name || 'Error',
    error: String(error?.message || error).slice(0, 500),
  })
  process.exit(1)
}
